### ISSUE TITLE
WordPress.org release preparations

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#1270]
## Feature Description

For the stable release we need to add a solid readme.txt file with good content and ideally some screenshots and FAQs. We can use #1269 as a starting point.

Also, we need to make sure the final code is GPL-compatible, and more things.

**To-do**

* [ ] Update readme.txt
* [ ] Add screenshots
* [ ] Offload template images to CDN (#1268)
* [x] Replace Gutenberg date picker (#789)
* [x] Use webpack externals for all `@wordpress/*` packages (e.g. `@wordpress/element`)  
  That code shouldn't be in the final bundle.
* [ ] Verify that internationalization and localization works as expected
* [ ] Verify that plugin still follows guidelines
* [ ] Remove beta updater (added in #2515)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Duplicate of #4136
