### ISSUE TITLE
Submit plugin to packagist.org

### ISSUE THREAD

**Issue by spacedmonkey** [GoogleForCreators/web-stories-wp#1271]
## Feature Description

Submit this plugin to packagist.org, so it can loaded via composer.

**To-do**

* [x] Make sure there is a composer-ready ZIP file being generated
* [x] Add `.gitattributes` file for people trying to get the source files (#4674)
* [x] Warn if running plugin from source (#1234)

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
@spacedmonkey Have you seen the composer bundle part in #1096?

Just submitting the plugin to Packagist wouldn't be enough, as the bundle needs to contain the built JS files, but not any `vendor` folder.

**Comment by swissspidy** [comment]
Closing for now. Packagist doesn't really support dist packages (https://github.com/composer/packagist/issues/903), so those are better fetched via WPackagist.
