### ISSUE TITLE
Add integration tests to inline text formatting

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#1612]
## Feature Description

Inline text formatting is in dire need of exhaustive integration testing, that can validate all the different possible interactions, including but not limited to:

#### In edit-mode: Inline collapsed selection
A.k.a. _inline style override_, works with bold, italic and underline only:
- [x] works by shortcut, design panel or both (note limitation in #1606)
- [x] shows correct state in design panel

#### In edit-mode: Inline non-collapsed selection
To be checked with single style and multi style selection:
- [x] check that design panel correctly reflects current selection
- [x] check that boolean toggles (bold, italic and underline) work by shortcut and design panel
- [x] check that selecting font weight, letter spacing or font color correctly styles selection
- [x] check that non-inline properties still applies to entire text field even though inline selection exists

#### Not in edit-mode: Single text field selection
All to be checked with single style and multiple styles present:
- [x] check that design panel correctly reflects state
- [x] check that boolean toggles (bold, italic and underline) work by design panel (doesn't work by shortcut yet, to be done in #1977)
- [x] check that selecting font weight, letter spacing or font color correctly styles entire text field

#### Not in edit-mode: Multiple text field selection
All to be checked with single style and multiple styles present between text fields:
- [x] check that design panel correctly reflects state
- [x] check that boolean toggles (bold, italic and underline) work by design panel (doesn't work by shortcut yet, to be done in #1977)
- [x] check that selecting font weight, letter spacing or font color correctly styles all text fields

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._
