### ISSUE TITLE
Call To Action Links

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#253]
As an editor I want to be able to add CTA links to a page

**[Feature Brief - Product spec: Links](https://docs.google.com/document/d/1k-TDKbrwgna3gpyMbwpsRvq3BqUlV3RJieQSFzOJMFM/edit#heading=h.ve4l7ve6f7a2)**

**Acceptance Criteria**
1. The Stories Format supports 2 types of CTA: 1-tap (Annotated) and 2-tap (Bottom Of The Page) links
2. You can only have one special element on the top grid layer. This means you:
Can only have a 1-Tap CTA OR a page attachment but not both on a page 
Can have 2-Tap links with either a 1-Tap link OR a page attachment on the same page 
Can have as many 2-Tap links on the page as you want
3. 1-click links, we only allow one CTA layer per page, but that layer can contain multiple 1-click links 
4. 2-Tap 
First tap opens a tooltip to expose a link out icon which when tap on takes you to the desired location.
5. 1-tap
You can think of 1-Tap CTA as a grouping of links that must reside in a container on the bottom 20% of the page.

See the **[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=2806%3A201)** for more details

### Task list:
- [x] Initial link implementation with 2-tap only
- [x] Fetch page description and image (requires server-side code) + loading state indicators
- [x] Ability to change the description and image
- [x] Visual guide for 2-tap / 1-tap + automatic conversion
- [x] URL Validation
- [x] Navigation & system layer safe zone
- [x] Instruction modal
- [ ] Keyboard shortcuts
- [ ] Interaction with drop targets
- [ ] Inline text links

**Comment by jauyong** [comment]
Hey @wassgha do you have an estimate for the remaining work on this?

**Comment by pbakaus** [comment]
Closing this for now, due to de-prioritization of 1-tap links.
