### ISSUE TITLE
Design Panel - UI Only

### ISSUE THREAD

**Issue by jauyong** [GoogleForCreators/web-stories-wp#255]
This ticket is a follow up to #99 and is for the UI of the design panel only. Functionality will be done in other tickets.

[Feature Brief - Epic: Selection & In-place Editing
](https://docs.google.com/document/d/1_3-_v4zH6bW9hOplOO8wYxj8l4C0soMgEbD7XLiXrrg/edit#)

### Components included
1. Input field (potentially prefixed), allowing different types
1. Borderless input with one or many inputs (see "rotation" and "padding"), prefix can be text or icon (see "line height")
1. Dropdown
1. Icon buttons with single state (e.g. "mirror"), dual state (e.g. "lock/unlock") or selected/unselected state (e.g. "underline").
1. Switch (see background image)
1. Button (see "set as background image" and "reset size")
1. "Row" component to align multiple components, optional separator (see before "reset size")

### Components not included
1. Font picker
1. Color picker
1. Image picker

### To-do
- [x] Dropdown component
- [ ] ~Panel re-organization (Will be handled by separate panel functional PRs and issues  )~
- [x] Slide to change on numeric inputs (PR #389)
- [x] ComboBox component
- [ ] ~Style the image upload component correctly (for example for the video poster image) (Will be handled separated issue #259  )~
- [x] Remove `assets/src/edit-story/components/panels/font.js` since it is redundant and obsolete (PR #412)

**[Design](https://www.figma.com/file/Cd9iacVknHK62RO4pRwb68/Stories-Editor?node-id=0%3A1)**

**Comment by jauyong** [comment]
Hey @obetomuniz @ndev1991 what is the estimate for the remaining work on this?

**Comment by ndev1991** [comment]
> Hey @obetomuniz @ndev1991 what is the estimate for the remaining work on this?

@jauyong panel reorganization will be done separately as @barklund mentioned. So the remaining things are combobox(dropdown) and Style the image upload component correctly (for example for the video poster image). I'm working on the customdropdown and it will be done by this week. And some reviews will be handled on Monday. And also on Monday I can handle the style the image upload component. So it should be done by Tuesday morning
