### ISSUE TITLE
Move Storybook deployment to GitHub actions

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#2796]
## Task Description

See https://github.com/google/web-stories-wp/issues/2472#issuecomment-650440917 for context.

We need to ensure we upload the templates for branches, similar to how we upload assets to the wiki.
However, this should perhaps be an opt-in feature. Not every branch needs to be added there.

**Done:**

* [x] Move Storybook deployment to GitHub actions

**To-do:**

Depending on the need:

* [ ] Skip QA deployment to wiki for PRs with a certain label? e.g. `Skip Deployment`
* [ ] Enable QA deployment to gh-pages branch.
* [ ] Maybe [redirect](https://help.github.com/en/enterprise/2.13/user/articles/redirects-on-github-pages) `https://google.github.io/web-stories-wp/` to `https://google.github.io/web-stories-wp/master/`? Otherwise keep master branch at root, and put branches in `https://google.github.io/web-stories-wp/refs/123/` or something.

**Comment by swissspidy** [comment]
Maybe easier if the assets deployment part is manual for now if there won't be many changes right now.
