### ISSUE TITLE
DX Improvements

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#319]
_WIP_

**Ideas:**

* [ ] Use something like yarn workspaces or Lerna to make distinction between packages clearer (#1735)
* [ ] React Fast Refresh for the editor & dashboard (#3689)
* [ ] Improving local development environment (#2521)
* [ ] Improving storybook playground (#374)
* [x] Auto-deployment for pull requests (#1398)
* [x] Improve Getting Started documentation (#1476)
* [x] Improve build/release process (auto upload artifacts, add commit hash to version number, etc.) (#1096)
* [x] Issue and PR templates (#304)
* [x] Use code owners feature (#379)
* [x] Implement [PHPStan](https://github.com/phpstan/phpstan)
* [x] Adopting a way to keep track of bundle size ([bundlesize](https://github.com/apps/bundlesize), [compressed-size-action](https://github.com/preactjs/compressed-size-action), [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer))
* [x] Adopting something like [Release Drafter](https://github.com/marketplace/actions/release-drafter) to keep an up-to-date changelog (#325)

------

**Prior Art:**

* Local development environment using Docker (#138)
* [Storybook](https://google.github.io/web-stories-wp/)
* GitHub Action to update list of bundled Google Fonts (#131)
* Adopting Prettier for (almost) all file types (#156)
* Improving linter config for things like license headers  (#245)
* Automating some changes to SVGs (#244, #315)
