### ISSUE TITLE
Improve PHP test coverage

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#328]
We'll probably heavily refactor the PHP code base at some point, which means we need some tests covering the current logic.

Especially for things like loading fonts, filtering KSES, passing the right config to the editor, etc.

**To-do:**

In a first PR:

* [x] Ignore `web-stories.php` from coverage
* [x] Ignore `uninstall.php` from coverage
* [x] Move `includes/edit-story.php` to `includes/templates/admin/edit-story.php`
* [x] Move `includes/templates/single-web-story.php` to `includes/templates/frontend/single-web-story.php`
* [x] Extract contents of `\Google\Web_Stories\Dashboard::render()` into `includes/templates/admin/dashboard.php`
* [x] Ignore `includes/templates` from coverage

In subsequent PRs (one for each class / file), add missing tests for all classes.

| Class               | Owner       | Done |
|---------------------|-------------|------|
| `Admin`             |             |      |
| `Dashboard`         |             |      |
| `Database_Upgrader` |             |      |
| `Discovery`         |             |      |
| `Embed_Blok`         |             |  ✅    |
| `Fonts`         |             |      |
| `KSES`         |             |      |
| `Media`         |             |      |
| `Plugin`         |             |  ✅    |
| `Story_Post_Type`         |             |  ✅   |
| `Story_Renderer`         |             |      |
| `Template_Post_Type`         |             |   ✅   |
| `Updater`         |  N/A        |      |
| `Assets`             |             |   ✅    |
| `Document_Parser`             |             |      |
| `Publisher`             |             |      |
| `Types`             |             |   ✅    |
| `Embed_Controller`             |             |       |
| `Fonts_Controller`             |             |       |
| `Link_Controller`             |             |       |
| `Stories_Autosaves_Controller`             |             |       |
| `Stories_Base_Controller`             |             |       |
| `Stories_Controller`             |             |       |

For the end goal of having average PHP coverage of ~90%

**Comment by swissspidy** [comment]
@spacedmonkey As you suggested, we can re-purpose this ticket to increase test coverage.
