### ISSUE TITLE
CUJ Reporter Improvements

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3411]
## Task Description

* [ ] Add tests for most of the logic
* [ ] Allow multiple tests for same action (https://xwp.slack.com/archives/CCCAUAH6F/p1595532621189000)
* [ ] Aggregate results with those from E2E tests (which would need its own CUJ reporter...)

**Comment by swissspidy** [comment]
Closing in favor of #8808
