### ISSUE TITLE
Text sets: Add text sets panel

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#4080]
## Feature Description

Add a text set panel:

- [ ] Use Pill UI created in #3967 for filtering the text sets
- [ ] Get all text sets defined in data structure in #3965
- [ ] Display them using component defined in #4077
- [ ] Add them to stage on click using `useInsertSet` defined in #3966 
- [ ] Add integration tests for entire panel (TBD in #4514 )

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

_Please fill this section before commencing issue resolution_.
