### ISSUE TITLE
Refactor design panel logic

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#4104]
## Feature Description

I want to completely overhaul how the design panels are structured internally.

For instance, I want the `sizePosition` panel to just be:

```js
function SizePositionPanel() {
  return (
    <SimplePanel
      name="size"
      title={__('Size & position', 'web-stories')}
    >
      <MakeBackground />
      <Position />
      <Size />
      <Rotation />
   </SimplePanel>
  );
}
```

And then each of these _row_'s of input(s) (let's call them _input groups_) will have the same internal structure greatly reducing overlap between them.

They're all essentially doing these 4 things in order:

1. Check if it should render at all (e.g. `MakeBackground` above, that should only render for media elements)
1. Get current value(s)
1. Create update logic (can be pretty complex for some types of inputs, e.g. width/height with both optional lock and min/max values)
1. Render `<Row />` with relevant components

## Todo

I think it makes sense to do this work in two PR's:

### PR 1
- [ ] Create design panel context to avoid passing all these props around: `selectedElements, submittedSelectedElements, pushUpdate,  pushUpdateForObject`.
- [ ] Split existing design panels into _input group_ components

### PR 2
- [ ] Generalize logic between _input groups_ where applicable

When all this is done, panels can be "re-shaped" as desired in the new design overhaul. I do however recommend this body of work first that keeps everything as-is (will also mean that tests don't need to be re-written but will function as a check on quality of refactor).

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

* Everything looks and works exactly as know
* Number of lines of code is greatly reduced
* All panels are extremely simple, input groups are as simple as can be reducing overlap between them.

## Implementation Brief

_See above_.

**Comment by swissspidy** [comment]
@barklund Just mentioning #732 / #2767 here in case the refactor makes that one easier to implement.

**Comment by bmattb** [comment]
This will not be ready for the v1.2 release on Wed. moving to 1.2.1
