### ISSUE TITLE
QA - Test of the Unsplash & Coverr 3P integration

### ISSUE THREAD

**Issue by bmattb** [GoogleForCreators/web-stories-wp#4186]
## Task Description

Please ensure that the integration of the 3rd Party media providers is working as expected.

User is able to

- [ ] Browse images from Unsplash / Coverr
- [ ] Filter images from Unsplash / Coverr
- [ ] Insert images from Unsplash / Coverr
- [ ] Select and deselect an Unsplash category to view images for it.
- [ ] Search videos and images in both Unsplash and Coverr.
- [ ] Images/videos inserted via Unsplash/Coverr render properly in the output AMP story.
- [ ] Images/videos inserted via Unsplash/Coverr can be manipulated without issues in the canvas.
- [ ] Pagination in the media gallery works as expected, especially when switching between provider tabs and performing things such as search, selecting a category, etc.

**Comment by diegovar** [comment]
You will need to enable the media3pTab and coverrTab flags to test this

**Comment by bmattb** [comment]
When would we be able to start this testing? cc: @csossi

**Comment by diegovar** [comment]
Hi Claudio, do you think you'll have bandwidth to test this?

**Comment by csossi** [comment]
sure, @diegovar - this the extent of the scope here?:
User is able to

 Browse images from Unsplash / Coverr
 Filter images from Unsplash / Coverr
 Insert images from Unsplash / Coverr

**Comment by diegovar** [comment]
Sorry for the late reply. Note that Coverr provides only videos, not images.

I'd add the following:

- Select and deselect an Unsplash category to view images for it.
- Search videos and images in both Unsplash and Coverr.
- Images/videos inserted via Unsplash/Coverr render properly in the output AMP story.
- Images/videos inserted via Unsplash/Coverr can be manipulated without issues in the canvas.
- Pagination in the media gallery works as expected, especially when switching between provider tabs and performing things such as search, selecting a category, etc.

**Comment by diegovar** [comment]
Hi Claudio, any updates on this?

**Comment by csossi** [comment]
Clicked the arrow in order to see available categories:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/d9b1e59c-e046-4575-b269-c6b7b8959416)
Categories appeared. Selected "Travel"
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6ee54807-75ef-4b16-90fe-5315ecfa5f96)
Images correctly filtered, but thought that arrow would reappear in case user wants to now select a diff category:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/0495748c-2926-464c-b1e7-edd34a75836f)


Also noticed that Search field is disabled/disappears on selecting image category, only reappearing when user deselects category. Is this intentional?

**Comment by diegovar** [comment]
Hi Claudio, thanks for spotting that. We've fixed #4404 by merging #4405 which means you should now be able to expand the categories section when a category is selected.

The search field being disabled while a category is selected is intentional.

**Comment by csossi** [comment]
Verified in QA
