### ISSUE TITLE
WordPress 5.6 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4788]
## Task Description

Previously: #3300

* [x] Update CI test matrix
* [ ] Do some manual testing for key affected areas
* [ ] Write/Update tests where applicable
* [x] Bump `Tested up to` value
* [ ] Consider dropping support for WordPress 5.3

**Comment by swissspidy** [comment]
https://core.trac.wordpress.org/changeset/49102 might be relevant

**Comment by swissspidy** [comment]
RC 1 is scheduled for next week: https://make.wordpress.org/core/5-6/

**Comment by spacedmonkey** [comment]
I think we should only drop support for a version of WordPres when it becomes expensive to support it

**Comment by spacedmonkey** [comment]
> Update CI test matrix

Current 5.5 is not referenced in the test matrix. Latest is and would cover 5.6. Should make the matrix, 5.3, 5.6, latest. 
 
> Do some manual testing for key affected areas

I did some manual testing and can't find any issues. Even read the change tickets in 5.6 and can't see anything that jumps out that would effect us 

>  Write/Update tests where applicable

As above, not sure what tests we need here. 

>  Bump Tested up to value

👍 
 
> Consider dropping support for WordPress 5.3

I think it is small effort to keep support. In my mind, 5.3 is a kind of LTS for WordPress, in the same way 4.9 was. As of today, 5.3 is 9.1% according to the [stats](https://en-gb.wordpress.org/about/stats/) page. I believe it still worth the effort to support. But after 5.6 release, these numbers may change. I think it is worth having these conversions again after 5.6 has been out for a month of two.

**Comment by swissspidy** [comment]
Let's start with updating the test matrix. If everything looks good there we can update our staging environment accordingly.

However, I don't think we should just make the matrix `5.3, 5.6, latest`

**Comment by swissspidy** [comment]
I think we can try out an optimized matrix like this for the unit tests.

```yml
matrix:
  php: ['7.4', '7.0']
  wp: ['latest']
  coverage: [false]
  include:
    - php: '7.4'
      wp: 'latest'
      coverage: true

    - php: '5.6'
      wp: '5.3'

    - php: '7.4'
      wp: '5.6'
      experimental: true

    - php: '7.4'
      wp: 'trunk'
      experimental: true

    - php: '8.0'
      wp: 'trunk'
      experimental: true
```

We'll likely also want to tackle #5338 to run E2E tests against both 5.3 and latest / 5.6
