### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4789]
## Task Description

Once PHP 8 is out and the WordPress PHPUnit test suite supports it, we should make sure the plugin works smoothly on PHP 8.

- [x] CI: Ensure unit tests can be run with PHP 8 (#5608)
- [ ] ~Update local dev environment to support PHP 8~ -  necessary?
- [ ] ~Update E2E tests to run in PHP 8 in GHA~ - necessary?
- [x] Fix any issues with code found in testing. (#5609)
- [x] Update / fix any composer dependencies affected by upgrade.  (#5608)

See also: #4788 #5344

**Comment by spacedmonkey** [comment]
In my testing, I could not easily get phpunit test running in PHP 8.0. See https://github.com/google/web-stories-wp/pull/5472

There were a number of issues here. 
- The hard platform requirement of 5.6 needs to be removed. Packages like php-object-mocks, does not support 5.6 - 8.0
- Doing a composer install, with a lock file that contains dependencies that only work on 5.6 to 7.4, means we need to do a composer install.
- [ampproject/amp-wp](https://github.com/ampproject/amp-wp) does not support 8.0 at this time. 

I think we need to give this sometime for the amp-wp team to support PHP 8.

**Comment by bmattb** [comment]
@o-fernandez - target as per @swissspidy is v1.3

**Comment by swissspidy** [comment]
Here's how it was implemented for the AMP plugin: https://github.com/ampproject/amp-wp/pull/5475

> I think we need to give this sometime for the amp-wp team to support PHP 8.

If we could make this work with dev-develop version of the amp-wp repo for now that'd be good.

**Comment by swissspidy** [comment]
@spacedmonkey should we split this up into one ticket for making tests work, and one for fixing issues?

**Comment by bmattb** [comment]
@spacedmonkey will create the associated tix for this epic

**Comment by spacedmonkey** [comment]
@swissspidy I do think it is required to enable running PHP 8 locally. We have to able to test it locally to valid it works. 

Related: https://github.com/docker-library/wordpress/issues/540

**Comment by spacedmonkey** [comment]
Looks like there is some progress. https://github.com/docker-library/wordpress/pull/551 but it is blocked https://github.com/Imagick/imagick/issues/358

**Comment by swissspidy** [comment]
@spacedmonkey Can you create a ticket for updating our local env once those images are published?

In the future we could then maybe switch to wp-env (#2521)

**Comment by spacedmonkey** [comment]
Ticket created #5626

**Comment by spacedmonkey** [comment]
I think we should remove #2521 from this epic and make PHP 8.0 support as done. Our current docker env supports PHP 8.0 so #2521 is not required.
