### ISSUE TITLE
Conflict with Cloudflare Web Application Firewall

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#4805]
**If you are coming from the support forums or encounter the following issue, please read carefully.**

This is a tracking ticket for the work on ensuring Web Stories for WordPress does not cause issues with the [Cloudflare Web Aplication Firewall (WAF)](https://support.cloudflare.com/hc/en-us/articles/200172016-Understanding-the-Cloudflare-Web-Application-Firewall-WAF-) or similar solutions.

Rules that so far have been identified as possibly causing conflicts:

* Cloudflare Specials > 100173 XSS, HTML Injection - Script Tag
* OWASP mod_security ruleset 981176

A similar conflict exists with Sucuri's WAF.

**Who's affected?**

The Cloudflare WAF is available to Pro, Business, and Enterprise plans.

**How do I know I am affected?**

You are likely affected when using Cloudflare's WAF offering and you are unable to save or publish stories using Web Stories for WordPress.

**Workaround**

Cloudflare:

Add a custom [Firewall rule](https://developers.cloudflare.com/firewall/cf-firewall-rules) to disable the WAF for any Web Stories-related REST API requests, like so:

<img width="1134" alt="Screen Shot 2020-10-02 at 12 34 56 PM" src="https://user-images.githubusercontent.com/841956/95084872-c62a3400-071e-11eb-8998-44b4bfb7495b.png">

Sucuri:

Add `wp-json/web-stories` to the allowlist in the "Whitelist URL Paths" section.

**What is being done to fix this?**

We are still investigating this issue and will update this thread with any new findings.

* [ ] Check if REST API is fully functioning when opening the editor (#4790)
* [ ] Improved error messages if REST API requests fail (#1033)
* [x] Implement experimental workaround in the plugin (#4859, #5038)

**How can I follow progress on this issue?**

Subscribe to this issue using the "Subscribe" button in the sidebar:

<img width="310" alt="Screenshot 2020-09-25 at 11 06 42" src="https://user-images.githubusercontent.com/841956/94248769-336be700-ff1f-11ea-86ee-8db9578db1e0.png">

-----

**User reports so far**

* https://wordpress.org/support/topic/failed-to-save-the-story/
* https://wordpress.org/support/topic/cloudflare-waf-block-json-issues/
* https://wordpress.org/support/topic/failed-to-save-the-story-2/
* https://wordpress.org/support/topic/failed-to-save-the-story-error/

**Comment by swissspidy** [comment]
My first assumption was that the WAF kicks in because we save the full AMP HTML markup via the REST API, but preliminary testing by @LuckynaSan & @ernee showed that this doesn't happen in all cases. For example, some templates can be used and previewed/published just fine. But creating a blank new story fails  every time with a 403 error.

I haven't done any in-depth testing with various configurations yet myself, but I found some valuable old threads on this when Gutenberg faced the same issue:

* https://github.com/WordPress/gutenberg/issues/2704
* https://github.com/WordPress/gutenberg/issues/3527
* https://blog.cloudflare.com/protecting-everyone-from-wordpress-content-injection/ (mentioned by 2704)

Then, the [OWASP ModSecurity Core Rule Set (CRS)](https://github.com/coreruleset/coreruleset) added [some exceptions](https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf) for Gutenberg:

* https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1232
* https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1298

**Comment by swissspidy** [comment]
In version 1.1.0 of the plugin there will be an experimental workaround for this. To enable:

1. Add `define( 'WEBSTORIES_DEV_MODE', true );` to your **`wp-config.php`** file  
  (somewhere before the `/* That's all, stop editing! Happy publishing. */`) line)
1. In your WordPress admin, go to **Stories** -> **Experiments**
1. Toggle the **WAF Compatibility** checkbox and save the changes.
1. Create a new story!

**Comment by swissspidy** [comment]
Closing in favor of #5059

**Comment by mateusnds** [comment]
> **If you are coming from the support forums or encounter the following issue, please read carefully.**
> 


Thank You
