### ISSUE TITLE
Website Documentation Updates

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5275]
## Task Description

Things to add/improve

* [ ] Explain safe zone
* [x] Update screenshots
* [ ] Shortcodes
* [x] New embed blocks, theme integrations, etc.
* [x] Analytics  
  * Site Kit
  * [Default configuration](https://docs.google.com/spreadsheets/d/1HtseNH-BY-0R1PQyDTWAT5mvxDWG5b5bocjVov_xQN0/edit)
  * Mention that Site Kit + Tag Manager does not yet work (see https://wordpress.org/support/topic/great-start-but-lots-of-work-to-do-to-make-it-actually-usable-2/)
* [x] Monetization (Ads)
* [x] Captions (see https://wordpress.org/support/topic/upload-captions-format/)
* [x] Video optimization
* [ ] Custom meta boxes
* [ ] Extend FAQ
* [ ] ...anything suggested by support team
