### ISSUE TITLE
[Discovery] Optimize Percy Usage

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5410]
## Task Description

Let's optimize Percy usage so we don't unnecessarily waste resources. Need to consider if/how it makes sense for the project going forward.

* [x] Survey team about usefulness
* [x] Don't run Percy for draft PRs (if not already the case)
* [ ] Don't run Percy for certain types of PRs (e.g. docs changes)
* [x] Cancel previous workflow actions if a new one is starting (avoids multiple builds when pushing new commits quickly) (#5729)

**Comment by swissspidy** [comment]
Closing for now
