### ISSUE TITLE
Stabilize Custom Meta Boxes Support

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5519]
## Feature Description

Follow-up to #3134 to:

* [x] Turn on feature by default
* [x] Remove feature flag
* [x] Stabilize UI
* [x] Refactor code where needed
* [x] Fix bugs where needed
* [x] More testing with other plugins

Some plugins to test with:

* AiO SEO Pack
* Yoast SEO (needs upstream PR first)
* Polylang
* WPML

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by swissspidy** [comment]
Hi @samitron7, for landing this feature I'd like your eyes on the design.

Here's a quick explainer.

We've integrated the "meta boxes" feature from WordPress so the editor better supports existing publishing editing workflows, for example so users can customize their SEO configuration for stories just like they can for posts.

These meta boxes are essentially third-party content from other WordPress plugins that we have no control over, which we sort of embed into our editor.

For comparison, here's how such a custom meta box looks like in Gutenberg:

Collapsed (default):

<img width="1680" alt="Screenshot 2020-12-15 at 13 17 01" src="https://user-images.githubusercontent.com/841956/102214146-1b7d8100-3ed8-11eb-93a4-faf0c7f83acb.png">

Open:

<img width="1680" alt="Screenshot 2020-12-15 at 13 45 29" src="https://user-images.githubusercontent.com/841956/102216701-d3f8f400-3edb-11eb-837f-a945891bab2d.png">


And here's how we've currently implemented this in the editor:

Collapsed (default):

<img width="1680" alt="Screenshot 2020-12-15 at 14 13 18" src="https://user-images.githubusercontent.com/841956/102219474-d1000280-3edf-11eb-9c37-9277b081599a.png">

Open:

<img width="1680" alt="Screenshot 2020-12-15 at 14 13 28" src="https://user-images.githubusercontent.com/841956/102219496-d6f5e380-3edf-11eb-9d9e-d00307d36a6d.png">

As you can see, it is very similar. And I think it works very well this way, but perhaps there are some tweaks we can make.

Some clarifying notes:

* If you don't use any other plugins, there are **no UI changes** to the editor. Seeing this really requires installing & configuring another plugin.
* We have **no control** over the meta box content or styling. That means we cannot paint them in the way we like, except for the title area. Rest needs to be kept in the default styling.
* The collapsing, and sorting (up / down arrows) of the meta boxes is default WordPress behavior, and we don't have any control over it.

**Comment by samitron7** [comment]
@swissspidy I'm a little concern over the vertical height this has taken. If there a way we can hide everything inside an icon/cta and only expose the accordion menu when you click on the icon/cta? This looks problematic on small screens as it takes up a lot of real estate.

**Comment by swissspidy** [comment]
@samitron7 I could probably add such an icon/button next to the keyboard shortcuts button if that works? Need to test it though

**Comment by samitron7** [comment]
@swissspidy Would be great if we can do this. Let know and I can help get you a reasonable cta treatment if it works. Also, if we have no control over the metabox styling, it would be better to have the whole thing be one color versus the gray and white.

**Comment by swissspidy** [comment]
I actually think the gray header blends in much nicer with the rest of the editor than a white header; but I'll see how a CTA affects this.

**Comment by swissspidy** [comment]
@samitron7 I put something together here:

https://user-images.githubusercontent.com/841956/104297181-d80c3780-54c2-11eb-8bd5-825d37f0aaf4.mp4

Again, when a user/site doesn't have any third-party integrations, the editor will look the same as today:

<img width="1680" alt="Screenshot 2021-01-12 at 10 41 11" src="https://user-images.githubusercontent.com/841956/104297071-b27f2e00-54c2-11eb-8114-ce4d735d39ba.png">

Please let me know what you think.

**Comment by samitron7** [comment]
@swissspidy Yes, much much better!

**Comment by csossi** [comment]
Added the following and saved draft. Reopened and entered input remained:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/6f13e9ad-55bd-4899-a0de-7aff34863a8b)

However, on page reload the fields cleared:
![image.png](https://images.zenhubusercontent.com/5ea085e4704e72c0a99c6997/35d6acfc-a1d0-4f17-83c5-2e0c5112e92c)

**Comment by swissspidy** [comment]
@csossi I think you found the two fields that won't easily work 😅 

* The "translations" field is not a type-whatever-you-want field. You'd have to click on the plus to connect a post
* The focus keyphrase field seems buggy in AiO SEO. Try the meta description field or a field in the "social" tab

**Comment by csossi** [comment]
Verified in QA
