### ISSUE TITLE
Telemetry: User Timings Tracking

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#5785]
## Feature Description

There's benefit tracking [user timings](https://support.google.com/analytics/answer/1205784#UserTimings).

[Implementation](https://developers.google.com/analytics/devguides/collection/gtagjs/user-timings) would be simple:

```js
gtag('event', 'timing_complete', {
  'name' : 'load',
  'value' : 3549,
  'event_category' : 'JS Dependencies'
});
```

This could be done in a new `trackTiming()` (or similar) helper, which would be a small wrapper around `trackEvent()`).

```js
function trackTiming(time, name, category, label) {
  // ...
}
```

```js
const before = performance.now();
doSomething();
const after = performance.now();
trackTiming(after-before, name, category, label);
```

Or more elegant:

```js
function getTimeTracker(name, category, label) {
  const before = performance.now()
  return () => {
    const after = performance.now();
    trackEvent(...);
  };
}
```

```js
const trackTiming = getTimeTracker(name, category, label);
doSomething();
trackTiming();
```

Some ideas for things to track:

* [ ] Initial page load (will be skewed due to WP overhead)
* [x] Load time for text sets
* [x] Load time for templates
* [x] Load time for page layouts
* [x] Load time for media library
* [x] Load time for video poster generation
* [x] Time to save story
* [ ] Other interactions that are time-sensitive

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._
