### ISSUE TITLE
Prepare design implementation in workspace/editor

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6039]
## Task Description

Create all tasks relevant for the design overhaul of the main editor. For each of these major sections of functionality, create tickets for what needs to be done to update to the new design system including which new generalized design components needed:

- [x] General inspector panel
- [x] Page menu
- [x] Page title
- [x] Publish buttons
- [x] Carousel and mini-menu
- [x] Page grid mode
- [x] Media library
- [x] Third-party libraries
- [x] Shape library
- [x] Text library

These have been postponed to the second sprint to be prepared by UX team:
- Design panels
- Document panels
- Pre-publish panel
- Modals/dialogs/popups
- Snackbar
