### ISSUE TITLE
Packages: Move `tracking` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6047]
## Feature Description

* [ ] Move code from `/assets/src/tracking` to `/packages/tracking/src/`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `/packages/tracking/package.json` referencing its dependencies
* [ ] Create `/packages/tracking/README.md` with short documentation.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._
