### ISSUE TITLE
Prepare design implementation of panels and overlays

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6251]
## Task Description

Create the tasks relevant to the design overhaul of the panels and overlays in the editor. For each of these major sections of functionality, create tickets for what needs to be done to update to the new design system including which new generalized design components needed:

#### New components
- [x] Color input (move from editor codebase + update hex parsing logic): 3 https://github.com/google/web-stories-wp/issues/6456
- [x] Color swatch (move from editor codebase): 2 https://github.com/google/web-stories-wp/issues/6457 
- [x] Media picker (move from editor codebase + circle or square mode): 2 https://github.com/google/web-stories-wp/issues/6459
- [x] P2: Switch (move from editor codebase): 3 https://github.com/google/web-stories-wp/issues/6492
- [x] P2: Media display: 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6498
- [x] P2: Filter (optional image URL + ): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3360%3A63235)] https://github.com/google/web-stories-wp/issues/6499
- [x] P2: Fieldset (implement as actual `<fieldset>` + `<Fieldgroup>` component): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6500
- [x] P2: Radio (single + grouping): 3 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3447%3A64541)] https://github.com/google/web-stories-wp/issues/6501
- [x] P2: Pill (check radio-like group functionality + update storybook story): 1 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3447%3A64541)] https://github.com/google/web-stories-wp/issues/6502

#### New component variants
- [x] Toggle button (make sure design is finalized): 1 #6490 
- [x] Checkbox reverse label order: 1 https://github.com/google/web-stories-wp/issues/6458
- [x] P2: Lock toggle button (prebaked from toggle button): 2 https://github.com/google/web-stories-wp/issues/6493
- [x] P2: URL input (move URL parsing logic from editor): 2 https://github.com/google/web-stories-wp/issues/6494
- [x] P2: Multiline input (with/without count): 2 https://github.com/google/web-stories-wp/issues/6495

#### Design panels
- [x] Update no-selection "panel" (sizing + typography): 2 https://github.com/google/web-stories-wp/issues/6460
- [x] Update page background panel (title + color): 2 https://github.com/google/web-stories-wp/issues/6461
- [x] Update background size position panel (title + media display + toggles + tooltips): 2 https://github.com/google/web-stories-wp/issues/6462
- [x] Update background overlay panel (allow for all media + title + filter + color): 3 https://github.com/google/web-stories-wp/issues/6463
- [x] Update page attachment panel (order + url + link): 2 https://github.com/google/web-stories-wp/issues/6464
- [x] Update image accessibility panel (multiline): 2 https://github.com/google/web-stories-wp/issues/6465
- [x] Update video accessibility panel (media picker + input + multiline): 2 https://github.com/google/web-stories-wp/issues/6466
- [x] Update alignment panel (toggles + remove dividers + tooltips): 2 https://github.com/google/web-stories-wp/issues/6467
- [x] Update size+position panel (remove "set bg" + inputs + toggles + tooltips): 3 https://github.com/google/web-stories-wp/issues/6468
- [x] Update layer style panel (input): 1 https://github.com/google/web-stories-wp/issues/6469
- [x] Update link panel (URL + input + media picker): 2 https://github.com/google/web-stories-wp/issues/6470
- [x] Update preset panel (_make sure it still looks correct_): 1 https://github.com/google/web-stories-wp/issues/6471
- [x] Split text box panel from text style panel: 2 https://github.com/google/web-stories-wp/issues/6472
- [x] Update text style panel (dropdowns + inputs + toggles + color + tooltips): 3 https://github.com/google/web-stories-wp/issues/6473
- [x] Update text box panel (pills + color + input + toggle + tooltips): 3 https://github.com/google/web-stories-wp/issues/6474
- [x] Update border width panel (inputs + toggle + color + tooltip): 2 https://github.com/google/web-stories-wp/issues/6475
- [x] Update border radius panel (inputs + toggle + tooltip): 2 https://github.com/google/web-stories-wp/issues/6476
- [x] P2: Update video playback panel (title + checkboxes): 2 [[Figma] (https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6503
- [x] P2: Update video captions panel (title + input + fieldset): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6504
- [x] P2: Update animation panel (inputs + toggles + tooltips + fieldset): 3 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)]  https://github.com/google/web-stories-wp/issues/6505
- [x] P2: Update shape style panel (color): 1 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6506

#### Other panels
- [x] P2: Status (title + radios + input): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6513
- [x] P2: Publish (title + dropdowns + media selectors): 3 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6514
- [x] P2: Excerpt (multiline input): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6515
- [x] P2: Permalink (input): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6518
- [x] P2: Page advancement (switch + input): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6519
- [x] P2: Pre-publish panel (_make sure it still looks correct_): 1 [[Figma] (https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A94450)] https://github.com/google/web-stories-wp/issues/6520

#### Modals/dialogs/popups
- [x] P2: Snackbar (implement in editor): 2 [[Figma](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3398%3A83619)] https://github.com/google/web-stories-wp/issues/6521
- [x] P2: All dialogs (status check + title missing + post publish + preview error + media delete + media edit + missing upload permission + story delete + 3rd party terms + confirm page layout + retire old dialog component): 5 https://github.com/google/web-stories-wp/issues/6522

**Comment by miina** [comment]
Components/adjustments for design-system:
- Checkbox variant with [checkboxes being first, labels after](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3483%3A385) (currently it seems to be only the other way around):
<img width="443" alt="Screenshot 2021-02-17 at 12 12 13" src="https://user-images.githubusercontent.com/3294597/108189479-14116880-7111-11eb-8382-6f814e6cd846.png">

- [Media edit/upload button](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=5850%3A460) with circle/square variants :
<img width="502" alt="Screenshot 2021-02-17 at 12 15 37" src="https://user-images.githubusercontent.com/3294597/108189952-9ac64580-7111-11eb-97db-9af02de42143.png">
<img width="511" alt="Screenshot 2021-02-17 at 12 14 10" src="https://user-images.githubusercontent.com/3294597/108189955-9bf77280-7111-11eb-955c-0b925d333a21.png">
<img width="759" alt="Screenshot 2021-02-17 at 12 16 06" src="https://user-images.githubusercontent.com/3294597/108189958-9d289f80-7111-11eb-823d-1603cd1e92fc.png">

- Lock toggle. That's something that's used in various places, instead of using a general Toggle for it and passing the Lock/Unlock icons in everywhere, it would make more sense to have a separate lock toggle component (or variant)
<img width="503" alt="Screenshot 2021-02-17 at 12 18 04" src="https://user-images.githubusercontent.com/3294597/108190141-d82ad300-7111-11eb-8b51-d9b52a2331e8.png">

- [Pills with radio functionality](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=779%3A3687)

<img width="469" alt="Screenshot 2021-02-17 at 12 21 03" src="https://user-images.githubusercontent.com/3294597/108190458-4079b480-7112-11eb-942e-e45f3b3bcce8.png">

- [Dropdown for fonts](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=423%3A0) and author -- should we use what we have?

-  [For filters](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A198113): we could add toggles (or radios) that accept dynamic content like image or icon or sth else as the clickable display:
<img width="579" alt="Screenshot 2021-02-17 at 12 28 28" src="https://user-images.githubusercontent.com/3294597/108191612-a155bc80-7113-11eb-86e7-2e29611c667e.png">


 Components we already have but might be good to move over to design-system and add Stories, too:
- [Saved colors](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3404%3A202243) and [saved text style](https://www.figma.com/file/bMhG3KyrJF8vIAODgmbeqT/Design-System?node-id=3399%3A78246) items: default / edit mode / semi-transparent variant (for colors)
- Toggles that accept icon (e.g. bold, italic, etc.) -- we can probably just use the button component?
- Toggles that behave as radios (e.g. text alignment) -- should we just use the button component and not make these actual radios?
- [Color input](https://www.figma.com/file/NHHMwIfxMnz39NxqkrFb7R/Stories-Post-Stable?node-id=1980%3A217741) -- this needs implementing a new set of rules for the hex input:
<img width="841" alt="Screenshot 2021-02-17 at 12 35 27" src="https://user-images.githubusercontent.com/3294597/108192187-407ab400-7114-11eb-85e8-cb2ef751a49e.png">

**Comment by barklund** [comment]
This has been completed!
