### ISSUE TITLE
Redesign: Update icons in the design system

### ISSUE THREAD

**Issue by barklund** [GoogleForCreators/web-stories-wp#6299]
## Task Description

- [x] Move design system 24x24 dashboard icons to dashboard icon folder
- [x] Remove all other other icons from design system
- [x] Export all new icons from Figma in 32x32 box
- [x] Import all new icons to design system
- [x] Update buttons to not scale icons, but keep 32x32 box centered regardless of button size
