### ISSUE TITLE
Release Automation Tweaks

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#6424]
## Task Description

* [x] Improve pre-flight checks
  * [x] Check for changelog entry in `readme.txt`
* [x] Fix bash commands
* [x] (Post-)release version bumps on `main`
* [x] Figure out how to trigger Firebase deployment for static assets ([as per known limitation](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token))
* [x] SVN user for deployments
* [x] Documentation

**Comment by swissspidy** [comment]
Some resources for pushing to main:

https://github.com/benjefferies/branch-protection-bot
https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token
