### ISSUE TITLE
Packages: Move `patterns` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7824]
## Task Description

**Context:**

The design system currently loads some patterns-related code from `edit-story` (which itself relies on the design system), causing a circular dependency.

Every util functions around patterns (i.e. dealing with hex and rgb colors) should be moved to a dedicated package.

A proof-of-concept has been added in #6902 / https://github.com/google/web-stories-wp/tree/f02da9e83a879b316e31b7d13bd62bd1dc8c9014/packages/patterns/src that shows which utils can be potentially moved.

**To-Do:**

* [ ] Move `assets/src/design-system/components/hex/getHexFromValue.js` + tests to `packages/patterns/src`
* [ ] Move `assets/src/design-system/components/hex/getPreviewText.js` + tests to `packages/patterns/src`
* [ ] Move pattern-related utils and test from `assets/src/edit-story` to `/packages/patterns/src`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `packages/patterns/package.json` referencing its dependencies
* [ ] Create `packages/patterns/README.md` with short documentation.
* [ ] Bonus: add tests for utils that don't have any yet
* [ ] Bonus: add JSDoc type definitions, and add JSDoc do utils which don't have any yet
