### ISSUE TITLE
Packages: Move `units` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7825]
## Task Description

**Context:**

`assets/src/edit-story` contains utils like `getBox`, `UnitsProvider`, constants like `PAGE_HEIGHT` and `PAGE_WIDTH`, and more that are currently used by `assets/src/dashboard` and `assets/src/animation`.

These interdependencies need to be eliminated by moving these to a dedicated package.

See https://github.com/google/web-stories-wp/tree/try/next-level-packages/packages/units for inspiration / proof-of-concept.

**To-Do:**

* [ ] Move `assets/src/edit-story/units` + tests to `packages/units/src`
* [ ] Move related constants from `assets/src/edit-story/constants.js` to `packages/units/src`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `packages/units/package.json` referencing its dependencies
* [ ] Create `packages/units/README.md` with short documentation.
* [ ] Bonus: add tests for utils that don't have any yet
* [ ] Bonus: add JSDoc type definitions, and add JSDoc do utils which don't have any yet

**Comment by swissspidy** [comment]
@spacedmonkey This one might be a nice low hanging fruit to pick up sometime to help advance efforts on package reorganization. PTAL and let me know if you have any open questions.
