### ISSUE TITLE
Packages: Move `media` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#7826]
## Task Description

**Context:**

Media related utils need to be moved into their own package so they can be used by story-editor, dashboard, and wp-editor without any circular dependencies.

See https://github.com/google/web-stories-wp/tree/try/next-level-packages/packages/media for inspiration / proof-of-concept.

**To-Do:**

* [ ] Move any media-related utils and constants (See PoC above) + tests to `packages/media/src`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `packages/media/package.json` referencing its dependencies
* [ ] Create `packages/media/README.md` with short documentation.
* [ ] Bonus: add tests for utils that don't have any yet
* [ ] Bonus: add JSDoc type definitions, and add JSDoc do utils which don't have any yet

**Comment by swissspidy** [comment]
@spacedmonkey This one might be a nice low hanging fruit to pick up sometime to help advance efforts on package reorganization. PTAL and let me know if you have any open questions.

**Comment by spacedmonkey** [comment]
> This one might be a nice low hanging fruit to pick up sometime to help advance efforts on package reorganization. 

Agreed. I have worked a lot on media code, so I can pick this up easily. I wonder if their are other media utils in other parts of the code.

**Comment by spacedmonkey** [comment]
I would like to look into the number of utils we have called `getFileName`. See 

https://github.com/google/web-stories-wp/blob/ee9705291497f1108707d29cb04366ff04f94940/packages/e2e-test-utils/src/getFileName.js#L17

https://github.com/google/web-stories-wp/blob/1222255391a88bade1f3f8f8b6a5d03358e08605/assets/src/edit-story/app/media/utils/getFileName.js#L23

https://github.com/google/web-stories-wp/blob/da23d65cbca76c604350464f0538115d280a7a06/assets/src/edit-story/utils/getFileName.js#L17-L19

https://github.com/google/web-stories-wp/blob/da23d65cbca76c604350464f0538115d280a7a06/assets/src/edit-story/app/media/utils/useUploadVideoFrame.js#L107-L114

**Comment by swissspidy** [comment]
> > This one might be a nice low hanging fruit to pick up sometime to help advance efforts on package reorganization.
> 
> Agreed. I have worked a lot on media code, so I can pick this up easily. I wonder if their are other media utils in other parts of the code.

There might be for sure. The PoC linked above contains a few already, but more can be added of course.

I'd not add any React hooks or components to that package though. Just util functions.
