### ISSUE TITLE
PPCv2.0 - pop-up cleanup

### ISSUE THREAD

**Issue by BrittanyIRL** [GoogleForCreators/web-stories-wp#7917]
## Feature Description
This feature had its shoes tied together, we needed the initial popup ahead of the checklist but we needed the checklist to really finish up the popup. 

This ticket is now for tying up all the popup related loose ends. Each of these can be it's own PR.

- [x] Adjust both help center and new checklist toggle buttons to take up less space (working with design on this) #8088 
- [x] Checklist popup should not collapse when clicks outside of it occur. It should only collapse when the 'x' close button is clicked.  #8112
- [ ] Implement Badge count of checklist toggle #8115 
- [ ] In the initial set up, we reused a lot of the help center pop up and didn't really name anything as 'shared', clean up the files where possible for both helpcenter and checklist popups to make it clear what's shared. 

## Additional Context

https://www.figma.com/file/1YM3jA9h4QGc4xLdyaXIJS/Stories-Sprint-1.7?node-id=8378%3A2077

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance Criteria

In LTR the checklist shows up to the right of the help center. 

In RTL the checklist shows up to the left of the help center. 

Badges work the same as they have in the panel: no issues listed on a new story, when priority issues are exposed then that shows up as a red badge with a number. 

Popup should not close when clicked out of it or when a thumbnail or title are clicked.

**Comment by BrittanyIRL** [comment]
While the initial popup was built based on the help center, we should still use this ticket to clean everything up. We should also handle this: 
<img width="352" alt="Screen Shot 2021-06-22 at 10 44 49 AM" src="https://user-images.githubusercontent.com/10720454/122974270-f9f9c800-d346-11eb-9dd0-a5b3ac65673e.png">

**Comment by BrittanyIRL** [comment]
Moving the refactor to share components between helpCenter and checklist to its own follow up ticket.
