### ISSUE TITLE
Packages: Move `elements` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8125]
## Feature Description

The dedicated `elements` package provides various APIs to register & retrieve element types.

**References:**

* [Package organization doc](https://docs.google.com/document/d/1ImRe9wYKWGCAZiq3jro5KLpSJK_NMKXHC6FWqs3nwl0/edit#)
* Proof-of-concept implementation: https://github.com/google/web-stories-wp/tree/try/next-level-packages/packages/elements/src

**To-do:**

* [ ] Move some of the code from `/assets/src/edit-story/elements` to `/packages/elements/src/`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `/packages/elements/package.json` referencing its dependencies
* [ ] Create `/packages/elements/README.md` with short documentation.

### Blockers ⚠️

* [ ] Remove any references to specific element types. For example, `createPage` references the `shape element` type. Move this util to story editor instead.
* [ ] Need a good place to reference rich-text related utils. (new `rich-text` package?)
* [ ] Need a good place to reference masks. (new `masks` package?)

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._
