### ISSUE TITLE
Packages: Move `rich-text` to new structure

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8126]
## Feature Description

This proposed `rich-text` package is intended to be a small wrapper around `draft-js`.

The dedicated `elements` package provides various APIs to register & retrieve element types.

**References:**

* [Package organization doc](https://docs.google.com/document/d/1ImRe9wYKWGCAZiq3jro5KLpSJK_NMKXHC6FWqs3nwl0/edit#)
* Proof-of-concept implementation: https://github.com/google/web-stories-wp/tree/try/next-level-packages/packages/rich-text/src

**To-do:**

* [ ] Move some of the code from `/assets/src/edit-story/components/richText` to `/packages/rich-text/src/`
  Definitely **not** move `context.js` and `provider.js`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `/packages/rich-text/package.json` referencing its dependencies
* [ ] Create `/packages/rich-text/README.md` with short documentation.

### Blockers ⚠️

* The proof-of-concept contains the `MULTIPLE_VALUE` constant, but it doesn't really make sense to live there. Needs a better home.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._
