### ISSUE TITLE
Packages: create new `react` package

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8159]
## Feature Description

As per the [package organization doc](https://docs.google.com/document/d/1ImRe9wYKWGCAZiq3jro5KLpSJK_NMKXHC6FWqs3nwl0/edit), this `react` package is intended to be a small wrapper around `use-context-selector` and provides a few useful hooks. It's deliberately not part of the `design-system` package as it is also needed by packages not depending on that.

**References:**

* [Package organization doc](https://docs.google.com/document/d/1ImRe9wYKWGCAZiq3jro5KLpSJK_NMKXHC6FWqs3nwl0/edit#)
* Proof-of-concept implementation: https://github.com/google/web-stories-wp/tree/try/next-level-packages/packages/react/src

**To-do:**

* [ ] Move some of the code from `design-system` and `edit-story` to `/packages/react/src/`  
  This includes but is not limited to:
  * `useBatchingCallback`
  * `useWhyDidYouUpdate` 
  * `createContext` and the like from `use-context-selector`
  * `useContextSelector`
  * `useCombinedRefs`
  * `useReduction`
  * `useUnmount`
  * `usePrevious`
* [ ] Update imports where necessary.  
  Use `@web-stories-wp/...` imports for anything that is already a package, relative imports for everything else.
* [ ] Create `/packages/react/package.json` referencing its dependencies
* [ ] Create `/packages/react/README.md` with short documentation.

**Open question:**

Maybe re-export React itself here and make any package depend on this one. Similar to `@wordpress/element`.

## Additional Context

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by spacedmonkey** [comment]
> Maybe re-export React itself here and make any package depend on this one. Similar to @wordpress/element.

👍

**Comment by spacedmonkey** [comment]
This would also make updating react a lot easier.

**Comment by spacedmonkey** [comment]
I made a start on this with - https://github.com/google/web-stories-wp/tree/feature/package-react

Looking at codebase, these functions are used from react 

useCallback, useEffect, useMemo, useRef, useState, forwardRef, memo, useLayoutEffect, useReducer, createRef, Fragment, StrictMode, Suspense, React. 

Do you still want to export these from react?

**Comment by swissspidy** [comment]
> Do you still want to export these from react?

Let's not do this for now. We can still do this later if deemed useful. Generally easiest to do in a second PR.

**Comment by swissspidy** [comment]
Amendment after discussion with @sayedtaqui:

Let's ship https://github.com/google/web-stories-wp/tree/feature/package-react already and create a second PR with exporting from React right afterward.

This will be needed for things like #8090 as well.
