### ISSUE TITLE
Enable feature: Eyedropper

### ISSUE THREAD

**Issue by miina** [GoogleForCreators/web-stories-wp#8247]
## Feature Description
Eyedropper is currently behind a feature flag, original PR: https://github.com/google/web-stories-wp/pull/7961

There a few things to do:
- [x] Fix and enable the Karma test for Eyedropper
- [x] Fix [the bug that Claudio found ](https://github.com/google/web-stories-wp/issues/262#issuecomment-875986055) Edit: Not able to reproduce this and it wasn't reported in the bug bash either -- might be an edge case to follow up later. Please file a bug for it if not able to reproduce.
- [x] Create patch file for `html-to-image`, see https://github.com/google/web-stories-wp/pull/8118#discussion_r665751490
- [x] Add a spinner for when the eyedropper is loading (image being generated). https://github.com/google/web-stories-wp/issues/8261 -
- [x] [DONE IN A SEPARATE PR] https://github.com/google/web-stories-wp/issues/8262 - tiny style fix. 
- [x] Mark the feature flag `true` by default (will enable the feature but allows to remove it easily if needed for some reason).

Creating a patch (instructions from Pascal):
1. Install regular version
2. Modify files directly in `node_modules/html-to-image/..`
3. Run `npx patch-package html-to-image`

**Comment by merapi** [comment]
@csossi is it QA Passed or only #8261?

**Comment by swissspidy** [comment]
@merapi only #8261.

**Comment by csossi** [comment]
Verified in QA
