### ISSUE TITLE
Update AMP Library Dependency

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#8574]
## Task Description

Version 2.1.4 of the AMP plugin is scheduled to be released this week.

It contains validator updates relevant for this plugin, specifically https://github.com/ampproject/amphtml/pull/35436, so we should update our dependency accordingly as soon as possible.

* [x] Bump `ampproject/amp-wp` to `2.1.4` in `composer.json`
* [ ] Bump `ampproject/amp-toolbox` accordingly if needed
* [ ] Run `composer update`
* [x] Update `WEBSTORIES_AMP_VERSION` in `web-stories.php`

**Comment by spacedmonkey** [comment]
ampproject/amp-wp 2.1.4 is not released yet. Moving back to sprint backlog.

**Comment by maitreyie-chavan** [comment]
ampproject/amp-wp 2.1.4 is now released - https://github.com/ampproject/amp-wp/releases/tag/2.1.4
